baseURL = 'https://nabeen.github.io/'
languageCode = 'ja-JP'
title = 'nabeen.github.io'
theme = 'dream'

enableRobotsTXT = true
hasCJKLanguage = true

[params]
zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = ""
# backgroundImageDark = ""

# images = ["img/global-background.jpg"]

author = "nabeen"
description = "nabeen の活動記録"
avatar = "images/avatar.png"
headerTitle = "nabeen.github.io"
motto = "nabeen の活動記録"

footerBottomText = "All Rights Reserved."

rss = true
 
# utterancesRepo = "nabeen/nabeen.github.io"
 
# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
 
# waline = true
# walineServer = ""
 
# email = "nabeen919@gmail.com"
 
siteStartYear = 2025
 
favicon = "images/avatar.png"
 
# Syntax highlighting
customSyntaxHighlighting = true
 
# options
stickyNav = false
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
reorderNavItems = ["search", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]
reorderShares = ["x"]

[params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []
 
[params.experimental]
jsDate = true
jsDateFormat = "yyyy-MM-dd"

[markup]
[markup.highlight]
noClasses = false
